" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

set history=200     " keep 200 lines of command line history
set ruler   		" show the cursor position all the time
set showcmd	    	" display incomplete commands
set incsearch		" do incremental searching
set number
set so=7
set expandtab		" uses spaces instead of tabs
set smarttab

" 1 tab = 4 spaces
set shiftwidth=4
set tabstop=4

" Displays a line length marker
set colorcolumn=120
set textwidth=120

set ai
set si
set wrap!

" Disables annoying error sounds
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
  set mouse=a
endif

colorscheme duna
